### PR TITLE
Fixes the below erros

### PR DESCRIPTION
**Pull request by jessp01**
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /opt/kaltura/app/alpha/apps/kaltura/lib/request/infraRequestUtils.class.php on line 70
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /opt/kaltura/app/alpha/apps/kaltura/lib/request/kIpAddressUtils.php on line 198
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /opt/kaltura/app/alpha/apps/kaltura/lib/monitor/KalturaMonitorClient.php on line 402
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /opt/kaltura/app/plugins/content_distribution/lib/kContentDistributionFlowManager.php on line 1685
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /opt/kaltura/app/plugins/content_distribution/lib/kContentDistributionFlowManager.php on line 1693

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/server/9498)

### CODE REVIEW

**Comment by erankor** [comment]
Looks good to me

**Comment by yossipapi** [comment]
Looks ok.

**Comment by jessp01** [comment]
So can I merge this?

**Comment by MosheMaorKaltura** [comment]
Reviewed

**Pull request merged**
