### PR TITLE
add support for S3 server-side encryption KMS and AES-256

### PR DESCRIPTION
**Pull request by doubleshot**
- Adds Amazon S3's SSE-S3 and SSE-KMS support to the S3 remote storage connector. SSE-C is NOT covered in this.
https://docs.aws.amazon.com/AmazonS3/latest/dev/serv-side-encryption.html
- Changes signature from default v2 to v4 to add support for SSE and New Europe and Asia datacenters

### CODE REVIEW

**Comment by doubleshot** [comment]
@MosheMaorKaltura Please review.

**Comment by MosheMaorKaltura** [comment]
@doubleshot , Review , no defect found.
Please fix brackets indentation according to coding convension.
not {
}
but 
{
} 

10x.

**Comment by doubleshot** [comment]
@MosheMaorKaltura Done, thanks!

**Comment by MosheMaorKaltura** [comment]
A new one created vs Kajam-11.16.0

**Pull request closed without merging**
