### PR TITLE
Mercury 13.0.0 plat 7837

### PR DESCRIPTION
**Pull request by shpiNi**

### CODE REVIEW

**Comment by MosheMaorKaltura** [comment]
This items needs to be implemented per type instead of checking type.
The validation can be added to ViewHistoryUserEntry & QuizUserEntry (or Just in UserEntry as default Impl.)

**Comment by shpiNi** [comment]
@MosheMaorKaltura , corrected according to your comment.

**Comment by MosheMaorKaltura** [comment]
Reviewed

**Comment by hilak** [comment]
reviewed by @erankor

**Pull request merged**
