### PR TITLE
Enhance http response headers

### PR DESCRIPTION
**Pull request by matsuu**
this patch enhances caching and compressing static files more aggresssively

### CODE REVIEW

**Comment by tan-tan-kanarek** [comment]
Thank you for your contribution.
Please describe what this change aimed to solve.

**Comment by jessp01** [comment]
@matsuu - we realize the changes are meant to make conditions more strict which is fine but we'd like to understand the actual issue you came across before we merge. Can you please reply?

Thank you,

**Comment by jessp01** [comment]
@matsuu, ping?

**Comment by matsuu** [comment]
i have lost interest in kaltura

**Pull request closed without merging**
