### PR TITLE
The root cause for SUP-4103 is that there are no thumbnails available an...

### PR DESCRIPTION
**Pull request by noam-arad**
The root cause for SUP-4103 is that there are no thumbnails available andd we try to generate them on the fly, in order to generate them we try to get the flavor_asset with the highest bitrate to get the thumbnails from, in this case the customer has external storage configured and "delete after export" so that some of the flavor assets are connected to file syncs that are deleted. The fix is to see if to get the flavor asset with the highest bitrate and a file sync that is in status "ready". Such a flavor asset doesn't have to exist but this is still a better solution than the one we have in place.

@yuly-roberman could you please review.

### CODE REVIEW

**Comment by tan-tan-kanarek** [comment]
Please change retrieveHighestBitrateByEntryId instead of creating a new method.
The existing method is used today only for finding the best source for thumbnailing, so it should be fixed for all thumbnailing flows.

**Comment by noam-arad** [comment]
It is also called from "updateVideoDimensions". I'd rather not affect the code of flows I am not sure what is done in them.

**Comment by tan-tan-kanarek** [comment]
updateVideoDimensions also requires a ready file-sync, that's exactly why I ask you to change the existing method, because until today it returned wrong data and I want you to fix it for all use cases.
As for the flows you're not sure about, that's why I'm here.

**Comment by noam-arad** [comment]
@tan-tan-kanarek The change was done and pushed.

**Pull request closed without merging**
