### PR TITLE
PSVAMB-10947 -> CR Change (The upgrade process cannot require any int…

### PR DESCRIPTION
**Pull request by TalDubovKaltura**
@jessp01

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/server/9428)

### CODE REVIEW

**Comment by jessp01** [comment]
Hi @TalDubovKaltura ,

It's better, however:
a. I don't see that you are setting (or prompting, for the -2 admin secret), to wit:
>     <session>
        <partnerId>-2</partnerId>
        <secret>@ADMIN_CONSOLE_PARTNER_ADMIN_SECRET@</secret>
        <sessionType>2</sessionType>
    </session>

See deployment/updates/scripts/xml/2018_04_27_mediaspaceNotificationsTemplates.template.xml for example
b. When you are done and have tested, I need this pushed to 16.2.0 as well since I need to release it.

**Comment by jessp01** [comment]
Also, all of these have the very same issue:
```
 # grep "prompt" /opt/kaltura/app/deployment/updates/ -r
/opt/kaltura/app/deployment/updates/scripts/xml/2020_03_30_User_Replied_To_Comment_AppSpecific.xml:        <serviceUrl>http://{prompt:Host name:}/</serviceUrl>
/opt/kaltura/app/deployment/updates/scripts/xml/2020_03_30_User_Deleted_A_Comment_AppSpecific.template.xml:        <serviceUrl>http://{prompt:Host name:}/</serviceUrl>
/opt/kaltura/app/deployment/updates/scripts/xml/2020_03_30_User_Replied_To_Comment_AppSpecific.template.xml:        <serviceUrl>http://{prompt:Host name:}/</serviceUrl>
/opt/kaltura/app/deployment/updates/scripts/xml/2020_03_30_User_Deleted_A_Comment_AppSpecific.xml:        <serviceUrl>http://{prompt:Host name:}/</serviceUrl>
/opt/kaltura/app/deployment/updates/scripts/xml/2020_03_30_User_Replied_To_Comment.template.xml:        <serviceUrl>http://{prompt:Host name:}/</serviceUrl>
/opt/kaltura/app/deployment/updates/scripts/xml/2020_03_30_User_Deleted_A_Comment.xml:        <serviceUrl>http://{prompt:Host name:}/</serviceUrl>
/opt/kaltura/app/deployment/updates/scripts/xml/2020_03_30_User_Replied_To_Comment.xml.backup:        <serviceUrl>http://{prompt:Host name:}/</serviceUrl>
/opt/kaltura/app/deployment/updates/scripts/xml/2020_03_30_User_Replied_To_Comment_AppSpecific.xml.backup:        <serviceUrl>http://{prompt:Host name:}/</serviceUrl>
/opt/kaltura/app/deployment/updates/scripts/xml/2020_03_30_User_Replied_To_Comment.xml:        <serviceUrl>http://{prompt:Host name:}/</serviceUrl>
/opt/kaltura/app/deployment/updates/scripts/xml/2020_03_30_User_Deleted_A_Comment.xml.backup:        <serviceUrl>http://{prompt:Host name:}/</serviceUrl>
/opt/kaltura/app/deployment/updates/scripts/xml/2020_03_30_User_Deleted_A_Comment_AppSpecific.xml.backup:        <serviceUrl>http://{prompt:Host name:}/</serviceUrl>
/opt/kaltura/app/deployment/updates/scripts/xml/2020_03_30_User_Deleted_A_Comment.template.xml:        <serviceUrl>http://{prompt:Host name:}/</serviceUrl>
```

**Comment by TalDubovKaltura** [comment]
@jessp01 
Secret has been added: https://github.com/kaltura/server/pull/9428/commits/c4fbc7fef6acb161828a45425c1ce6c22047857f

As for the other files, where do you these without the '<serviceUrl>@SERVICE_URL@</serviceUrl>'?

After approving this pull request I will push it also to 16.2.0.
Thank you Jess

**Comment by jessp01** [comment]
I see them in all the files I noted above. For example: https://github.com/kaltura/server/blob/Propus-16.3.0/deployment/updates/script/xml/2020_03_30_User_Replied_To_Comment_AppSpecific.template.xml#L4
https://github.com/kaltura/server/blob/Propus-16.3.0/deployment/updates/scripts/xml/2020_03_30_User_Deleted_A_Comment.template.xml#L4
https://github.com/kaltura/server/blob/Propus-16.3.0/deployment/updates/scripts/xml/2020_03_30_User_Replied_To_Comment_AppSpecific.template.xml



The change you made seems fine, Just run the `grep` from my comment in your clone and fix every such instance.

**Comment by TalDubovKaltura** [comment]
> I see them in all the files I noted above. For example: https://github.com/kaltura/server/blob/Propus-16.3.0/deployment/updates/script/xml/2020_03_30_User_Replied_To_Comment_AppSpecific.template.xml#L4
> https://github.com/kaltura/server/blob/Propus-16.3.0/deployment/updates/scripts/xml/2020_03_30_User_Deleted_A_Comment.template.xml#L4
> https://github.com/kaltura/server/blob/Propus-16.3.0/deployment/updates/scripts/xml/2020_03_30_User_Replied_To_Comment_AppSpecific.template.xml
> 
> The change you made seems fine, Just run the `grep` from my comment in your clone and fix every such instance.

@jessp01 I already ran it before and no file left with that, the links you attached is from 16.3.0 which still not includes the changes I added

**Comment by jessp01** [comment]
Yes. You can merge and push to 16.2.0 as well.

**Comment by TalDubovKaltura** [comment]
@jessp01 We don't need any permission from the BE Core? Can I push it for both branches? and I know we don't need here any deployment.

**Comment by jessp01** [comment]
You can check with Moshe Maor. I don't see why he should object but in any case, I must have it in 16.2.0 as I need to release the version.

**Comment by jessp01** [comment]
Any news?

**Comment by TalDubovKaltura** [comment]
@jessp01 I added just now the changes here to 16.2.0 with cherry-pick. as for 16.3.0 pull request, we will wait for Moshe to respond

**Comment by jessp01** [comment]
Building a new package and testing.

**Comment by jessp01** [comment]
All good on 16.2. Please be sure to push this to 16.3.0.

**Comment by jessp01** [comment]
@TalDubovKaltura, 
What's our status on this one? It needs to be merged into 16.3.0

**Comment by TalDubovKaltura** [comment]
@MosheMaorKaltura Can you confirm these changes?

**Comment by jessp01** [comment]
@TalDubovKaltura , @MosheMaorKaltura ,
How many more times am I expected to ask about this?
We've gone through a full dev cycle since I first reported it. I cannot release 16.3.0 until this is fixed.

**Comment by jessp01** [comment]
@zoharbabin - FYI.

**Comment by MosheMaorKaltura** [comment]
Reviewed
Notice to merge to the correct branch 16.4

**Comment by jessp01** [comment]
I need it merged to both. 16.3.0 cannot be released until this is merged to it.

**Comment by TalDubovKaltura** [comment]
@jessp01 merged to both 16.3 and 16.4, please approve.

**Pull request merged**
