### PR TITLE
Update README.txt

### PR DESCRIPTION
**Pull request by jo2012**
Developpers should not edit KalturaTestConfig.java.
they should edit the file propertie : test.properties

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @jo2012,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by jo2012** [comment]
ok, just signed it for this contrib.

**Comment by zoharbabin** [comment]
@tan-tan-kanarek @erankor

**Comment by tan-tan-kanarek** [comment]
Thank you

**Pull request merged**
