### PR TITLE
Lynx 12.5.0 plat 6357

### PR DESCRIPTION
**Pull request by noam-arad**

### CODE REVIEW

**Comment by noam-arad** [comment]
@anatolkaltura  according to @erankor  we should remove the sps-id=27 but I'm not sure if for all use-cases.

**Comment by anatolkaltura** [comment]
@noam-arad, @erankor 
Removal of 'sps-id=27' contradicts the existing code in - https://github.com/kaltura/play-server/blob/v3.0.0/lib/media/KalturaFfmpegParams.js#L316

**Comment by erankor** [comment]
To clarify - sps-id=27 MUST be used for live, and MUST NOT be used for vod. Not sure if this is currently the case or not.

**Comment by noam-arad** [comment]
verified that this doesn't affect live.

**Pull request merged**
