### PR TITLE
Kajam 11.9.0 plat 5097

### PR DESCRIPTION
**Pull request by shpiNi**

### CODE REVIEW

**Comment by hilak** [comment]
@shpiNi  Why do we need this? If you check the SaaS, we already have this HTTP notification - Flavor Asset Status Equals.Also, I don't think we should commit these templates to the server repo, but to the SaaS tag.

**Comment by shpiNi** [comment]
@hilak that notification requires a specific flavor params id and status. I can't find a reason for it not to be public.

**Comment by hilak** [comment]
@shpiNi  Where is the condition related to the flavor params ID?

**Comment by shpiNi** [comment]
@hilak in the notification you mentioned. mine simply has less conditions.

**Comment by hilak** [comment]
@shpiNi ok, didn't see that. And the content parameters?

**Pull request merged**
