### PR TITLE
Update copyright notice to 2016 [ci skip]

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @Atul9,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by jessp01** [comment]
@Atul9 - can you please sign the CLA and make a pull against 11.9.0?

**Comment by Atul9** [comment]
@jessp01 I tried that but I am getting "ERROR: #19 column email is not unique :(" I have entered my email id, but still it shows this error.

**Comment by KalturaCommunity** [comment]
What is the email addr you're trying to input? feel free to send to me in 
private at jess.portnoy@kaltura.com if you don't want to share it here.

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by jessp01** [comment]
Closing in favor of https://github.com/kaltura/server/pull/3860

**Pull request closed without merging**
