### PR TITLE
when checking if entry is done return true is entry status is already…

### PR DESCRIPTION
**Pull request by yossipapi**
… set to READY

### CODE REVIEW

**Comment by yossipapi** [comment]
@noam-arad please review.

**Comment by noam-arad** [comment]
Looks good

**Comment by MosheMaorKaltura** [comment]
The action ‘checkEntryIsDoneAction’ is not only checking but also calling kBusinessPostConvertDL::handleConvertFinished.
Did you verify this function will be called in the flow that you covered also when entry becomes ready.

**Comment by noam-arad** [comment]
handleConvertFinished should be called only if the entry is stuck in a non-ready state. Thus if the entry is ready there is no need for handleConvertFinished

**Pull request merged**
