### PR TITLE
Add protocol at the beginning of cdn white list

### PR DESCRIPTION
**Pull request by noam-arad**

### CODE REVIEW

**Comment by MosheMaorKaltura** [comment]
Approve.

**Comment by jessp01** [comment]
What about port?

**Comment by noam-arad** [comment]
We know that the API listens on port 80 for HTTP and 443 for HTTPS it is enough to return the protocol

**Comment by jessp01** [comment]
This is only true to SaaS. We should always code to consider alt ports. 
Especially since we also support CE and OnPrem from the same code base.

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
virtualconnect.kaltura.com

**Comment by noam-arad** [comment]
So your suggestion is to add the port received in $_SERVER['SERVER_PORT']?

**Comment by jessp01** [comment]
Yes.

**Pull request merged**
