### PR TITLE
SUP-8526 changed float formatting to avoid OS locale settings affect …

### PR DESCRIPTION
**Pull request by gonenradai**
…the number representation

### CODE REVIEW

**Comment by gonenradai** [comment]
zip file in the respective support ticket can be used to reproduce the issue (just need to make sure Windows locale setting use comma as decimal separator instead of dot).

**Comment by tan-tan-kanarek** [comment]
This client generator is not used anymore.
Please apply the fix in https://github.com/kaltura/clients-generator

**Comment by gonenradai** [comment]
@tan-tan-kanarek , @MosheMaorKaltura  
https://github.com/kaltura/clients-generator doesn't have a 11.19 branch yet...

**Comment by tan-tan-kanarek** [comment]
Created

**Pull request closed without merging**
