### PR TITLE
[C# API] Memory-efficient implementation of PostMultiPartWithFiles

### PR DESCRIPTION
**Pull request by IrmatDen**
Hello,

Due to how MemoryStream capacity is handled, going over 1'073'741'823 bytes start stressing the GC like crazy. A potential OutOfMemoryException is also thrown by HttpWebRequest if the network stream is buffering the data (which is the default behaviour).
The proposed changes solve this problem by totally bypassing the "fit everything in memory" before streaming and disable request stream buffering.

Impl. note: I had to create an inner private struct in a new region. I'm not too sure if a separate file is preferred; let me know if you'd like me to change this to another approach.

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @IrmatDen,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by zoharbabin** [comment]
@IrmatDen Can you please provide a test for the change? In what context did you discover the issue?

Thanks!

**Comment by IrmatDen** [comment]
@zoharbabin Sorry, not proper test case, except I had previously compiled & tested it on the autogenerated libs (also, mistakenly created a PR over there, see: https://github.com/kaltura/KalturaGeneratedAPIClientsCsharp/pull/1).

My claim about GC stress comes from [System.IO.MemoryStream.EnsureCapacity(...) implementation](http://referencesource.microsoft.com/#mscorlib/system/io/memorystream.cs,1416df83d2368912). Since int.MaxValue == 2,147,483,647 bytes, EnsureCapacity()'s exponential behavior falls apart at floor(int.MaxValue / 2), where the buffer is re-allocated/copied & gc'd on each write.

The context was just testing your C# API with some big video files, and the upload times were awful due to the double buffering combined to said capacity issue.

**Comment by tan-tan-kanarek** [comment]
Will be merged as part of https://github.com/kaltura/server/pull/2907.

**Pull request closed without merging**
