### PR TITLE
Jupiter 10.1.0 pyclient distrbution tests

### PR DESCRIPTION
**Pull request by flipmcf**
Adding Simple ContentDistribution Tests to python client.

### CODE REVIEW

**Comment by flipmcf** [comment]
git rebase --onto FTW #2203

**Comment by erankor** [comment]
Hi @flipmcf,

Sorry for the long delay (again :)), please reopen against the default branch (currently 10.8.0) and I'll merge it.

Thanks !

**Comment by jessp01** [comment]
Hello @flipmcf,

Hope you're well. I wonder if you missed Eran's request from Mar 26..? Can you please pull against 10.12.0?

**Comment by flipmcf** [comment]
I noticed it.  I just lost steam because I've already switched this pull between 3 branches already.

**Comment by erankor** [comment]
merged via a different pull - https://github.com/kaltura/server/pull/2586

Thanks !

**Pull request closed without merging**
